# Generated by Django 5.2.8 on 2025-11-28 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deportivo',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('color', models.CharField(max_length=50)),
                ('motor', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen_url', models.URLField(max_length=500, verbose_name='URL de Imagen')),
                ('id_deportivo', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Deportivo',
            },
        ),
        migrations.CreateModel(
            name='Ford100Anios',
            fields=[
                ('id_aniversario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='Mustang Edición Centenario', max_length=100)),
                ('motor', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('rines', models.CharField(max_length=100)),
                ('emblemas', models.CharField(max_length=200)),
                ('interior', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('disponible', models.BooleanField(default=True)),
                ('imagen_url', models.URLField(max_length=500)),
            ],
            options={
                'verbose_name': 'Ford 100 Años',
                'verbose_name_plural': 'Ford 100 Años',
            },
        ),
        migrations.CreateModel(
            name='PickUp',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('color', models.CharField(max_length=50)),
                ('motor', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen_url', models.URLField(max_length=500, verbose_name='URL de Imagen')),
                ('id_pickup', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Pick Up',
            },
        ),
        migrations.CreateModel(
            name='SUV',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('color', models.CharField(max_length=50)),
                ('motor', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen_url', models.URLField(max_length=500, verbose_name='URL de Imagen')),
                ('id_suv', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'SUV',
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_pago', models.CharField(max_length=50)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_pago', models.CharField(default='Exitoso', max_length=50)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SistemaApartado',
            fields=[
                ('id_apartado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_vehiculo', models.CharField(max_length=150)),
                ('tipo_vehiculo', models.CharField(max_length=50)),
                ('fecha_apartado', models.DateTimeField(auto_now_add=True)),
                ('enganche', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(default='Pendiente', max_length=50)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
